FROM node:20-alpine as build

WORKDIR /app


RUN npm install -g @microsoft/rush@5.133.4

COPY rush.json .

COPY common/config/rush/ ./common/config/rush/
COPY apps/client/ ./apps/client/
COPY apps/server/package.json ./apps/server/

RUN rush update

WORKDIR /app/apps/client

RUN npm run build

FROM nginx:1.27.4-alpine

COPY --from=build /app/apps/client/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
