version: '3.9'

# чтобы env-переменные были доступны в самом docker-compose-файле:
# docker-compose -f docker-compose.production.yml --env-file ./apps/server/.env.production up
# если рядом с docker-compose.yaml лежит файл .env, то docker-compose будет использовать его по-умолчанию
services:
  postgres:
    image: postgres:17
    restart: always
    container_name: postgres_container

    # Переменные, доступные внутри контейнера
    env_file:
      - ./apps/server/.env.production

    ports:
      - '5433:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.1.0
    restart: always
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server_container

    # Переменные, доступные внутри контейнера
    env_file:
      - ./apps/server/.env.production

    ports:
      - '${SERVER_PORT:-5000}:${SERVER_PORT:-5000}'

    depends_on:
      - postgres

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client_container

    ports:
      - '80:80'
